### ISSUE TITLE
Upload  MP4 video is rquested

### ISSUE THREAD

**Issue by 8807p3** [tanaikech/GeminiWithFiles#1]
Great  help  to me for this library.  When I sent  mp4   files. It tell me excess  upload file size.  Is there a revision?

**Comment by tanaikech** [comment]
Thank you for your comment. It's done in version 1.0.4. But, please be careful about the file size of the video file and the state of the uploaded file. If the video file is more than 50 MB, it cannot be used. And, if the state of the uploaded file is not active, please wait to change it to active.
