### ISSUE TITLE
request  code modify  for total token counts

### ISSUE THREAD

**Issue by 8807p3** [tanaikech/GeminiWithFiles#3]
Could you please modify the code to store the total token count in a variable instead of outputting it directly to the console? This would help me retrieve the token count and input it into a Google Sheet or another location. Thank you!

**Comment by tanaikech** [comment]
Thank you for your comment. Your suggestion was added and it was updated to v1.0.7. https://github.com/tanaikech/GeminiWithFiles?tab=readme-ov-file#exporttotaltokens
